"""
Generate CuRobo collision spheres for OMY-F3M from visual meshes.

Strategy:
- Arm links (link0~6, flange): modeled as cylinders.
  sphere_r = cross-section radius, n = ceil(length / R) for dense coverage
- Gripper fingers: thin elongated parts, use smaller spheres.

Usage:
    conda activate fetchbench
    python scripts/generate_omy_spheres.py

Output:
    third_party/curobo/src/curobo/content/configs/robot/spheres/omy_f3m.yml
"""

import os
import sys
import trimesh
import numpy as np
import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

MESH_DIR = os.path.join(REPO_ROOT, "InfiniGym/assets/urdf/omy_f3m/meshes")
OUTPUT_PATH = os.path.join(
    REPO_ROOT,
    "third_party/curobo/src/curobo/content/configs/robot/spheres/omy_f3m.yml",
)

LINKS = {
    "link0": "omy_f3m/base_unit.stl",
    "link1": "omy_f3m/link1.stl",
    "link2": "omy_f3m/link2.stl",
    "link3": "omy_f3m/link3.stl",
    "link4": "omy_f3m/link4.stl",
    "link5": "omy_f3m/link5.stl",
    "link6": "omy_f3m/link6.stl",
    "end_effector_flange_link": "omy_f3m/flange.stl",
    "rh_p12_rn_base": "rh_p12_rn_a/base.stl",
    "rh_p12_rn_r1": "rh_p12_rn_a/r1.stl",
    "rh_p12_rn_r2": "rh_p12_rn_a/r2.stl",
    "rh_p12_rn_l1": "rh_p12_rn_a/l1.stl",
    "rh_p12_rn_l2": "rh_p12_rn_a/l2.stl",
}

GRIPPER_LINKS = {"rh_p12_rn_base", "rh_p12_rn_r1", "rh_p12_rn_r2",
                 "rh_p12_rn_l1", "rh_p12_rn_l2"}


def cylinder_spheres(mesh):
    """Cylinder model: sphere_r = cross-section radius, spacing = R (dense)."""
    extents = mesh.extents
    bounds = mesh.bounds
    centroid = mesh.centroid

    main_axis = int(np.argmax(extents))
    cross_axes = [i for i in range(3) if i != main_axis]
    cross_r = min(extents[cross_axes[0]], extents[cross_axes[1]]) / 2.0
    length = extents[main_axis]

    sphere_r = cross_r
    n = max(2, int(np.ceil(length / sphere_r)))

    spheres = []
    for i in range(n):
        t = (i + 0.5) / n
        center = centroid.copy()
        center[main_axis] = bounds[0][main_axis] + t * length
        spheres.append({
            "center": [round(float(center[0]), 4),
                       round(float(center[1]), 4),
                       round(float(center[2]), 4)],
            "radius": round(float(sphere_r), 4),
        })
    return spheres, sphere_r


def gripper_spheres(mesh):
    """Gripper model: small spheres, spacing = R (dense)."""
    extents = mesh.extents
    bounds = mesh.bounds
    centroid = mesh.centroid

    main_axis = int(np.argmax(extents))
    cross_axes = [i for i in range(3) if i != main_axis]
    min_cross = min(extents[cross_axes[0]], extents[cross_axes[1]])
    length = extents[main_axis]

    sphere_r = max(min_cross / 2.0, 0.004)
    n = max(2, int(np.ceil(length / sphere_r)))
    n = min(n, 10)

    spheres = []
    for i in range(n):
        t = (i + 0.5) / n
        center = centroid.copy()
        center[main_axis] = bounds[0][main_axis] + t * length
        spheres.append({
            "center": [round(float(center[0]), 4),
                       round(float(center[1]), 4),
                       round(float(center[2]), 4)],
            "radius": round(float(sphere_r), 4),
        })
    return spheres, sphere_r


def main():
    sphere_cfg = {"collision_spheres": {}}
    total = 0

    print("Generating OMY-F3M collision spheres")
    print()
    print(f"  {'Link':<30s} {'N':>3s}  {'R':>7s}  {'CrossR':>7s}  {'Length':>7s}  Method")
    print(f"  {'-'*30} {'-'*3}  {'-'*7}  {'-'*7}  {'-'*7}  {'-'*10}")

    for link_name, stl in LINKS.items():
        m = trimesh.load(os.path.join(MESH_DIR, stl))
        m.apply_scale(0.001)

        main_ax = int(np.argmax(m.extents))
        cross_ax = [i for i in range(3) if i != main_ax]
        cross_r = min(m.extents[cross_ax[0]], m.extents[cross_ax[1]]) / 2.0
        length = m.extents[main_ax]

        if link_name in GRIPPER_LINKS:
            spheres, r = gripper_spheres(m)
            method = "gripper"
        else:
            spheres, r = cylinder_spheres(m)
            method = "cylinder"

        sphere_cfg["collision_spheres"][link_name] = spheres
        total += len(spheres)
        print(f"  {link_name:<30s} {len(spheres):>3d}  {r:>7.4f}  {cross_r:>7.4f}  {length:>7.4f}  {method}")

    sphere_cfg["collision_spheres"]["attached_object"] = None

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write("##\n## OMY F3M collision spheres\n")
        f.write("## Auto-generated by scripts/generate_omy_spheres.py\n")
        f.write("## Arm links: cylinder model (r=cross-section, spacing=R)\n")
        f.write("## Gripper: thin-part model (small r, spacing=R)\n##\n")
        yaml.dump(sphere_cfg, f, default_flow_style=False)

    print(f"\n  Total: {total} spheres")
    print(f"  Saved: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
